---
- name: Add solc repo
  apt_repository:
    repo: "{{ solc_repo }}" 
  become: yes
  run_once: true
  delegate_to: 127.0.0.1

- name: Install solc.
  apt: 
    name: solc
    state: present
  become: true
  run_once: true
  delegate_to: 127.0.0.1

- name: Compile contract
  shell: "solc --bin --abi --optimize {{ contract_src }}"
  register: byte_code
  run_once: true
  delegate_to: 127.0.0.1

- debug:
    msg: "Deploy contract result is 0x{{ byte_code.stdout_lines.3 }}"
  run_once: true

- name: Deploy contract
  uri:
    url: "{{ parity_url }}"
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "personal_sendTransaction"
      params:
        - from: "{{ contract_publish_from }}"
          data: "0x{{ byte_code.stdout_lines.3 }}"
        - "{{ contract_publish_from_unlockPass }}"
      id: 0
    return_content: yes
  register: contract_hash
  run_once: true


- debug:
    msg: "Deploy contract result is {{ contract_hash }}"
  run_once: true


- pause:
    seconds: 5

- name: Get contract address
  uri:
    url: "{{ parity_url }}"
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "eth_getTransactionReceipt"
      params:
        - "{{ contract_hash.json.result }}"
      id: 0
    return_content: yes
  register: contract_addr
  run_once: true

- name: Set contract json
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
  with_items:
    - { src: "contract.json.jn2", dst: "{{ contract_publish_output }}" }
  become: yes
  run_once: true
  delegate_to: 127.0.0.1

- debug:
    msg: "Contract address is {{ contract_addr.json.result.contractAddress }}"

