parity_path: /var/lib/parity
parity_url: "http://127.0.0.1:{{ parity_rpc_entries.port }}"
parity_config_path: "/etc/parity"
parity_config: "{{ parity_config_path }}/config.toml"
parity_spec: "{{ parity_config_path }}/spec.json"
parity_pwd: "{{ parity_config_path }}/auth.pwd"
parity_deb: "http://d1h4xl4cr1h0mo.cloudfront.net/v1.11.10/x86_64-unknown-linux-gnu/parity_1.11.10_ubuntu_amd64.deb"
parity_package: parity

nginx_config_path: "/etc/nginx"
nginx_includes_path: "{{ nginx_config_path }}/includes"


nginx_port: 80
nginx_ssl: true
nginx_ssl_port: 443
nginx_ssl_dhparam: /etc/ssl/{{ nginx_server_name }}.dhparam
nginx_ssl_certificate: /etc/ssl/{{ nginx_server_name }}.pem
nginx_ssl_certificate_key: /etc/ssl/{{ nginx_server_name }}.key
nginx_server_name: testnet.onlyoffice.io

nginx_auth_basic_login: onlyoffice
nginx_auth_basic_password: password

contract_validators_file: contracts/AdminValidatorList.sol
contract_validators_addr: "0x0000000000000000000000000000000000000005"

solc_repo: "ppa:ethereum/ethereum"
